/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSObject, NSMutableDictionary;
@protocol OS_dispatch_queue;

__attribute__((visibility("hidden")))
@interface MIApplicationArchiveManager : XXUnknownSuperclass {
	NSObject<OS_dispatch_queue>* _queue;
	NSMutableDictionary* _archiveMap;
}
+(id)defaultManager;
-(void).cxx_destruct;
-(void)clearArchives;
-(id)archiveMap;
-(BOOL)removeArchiveForIdentifier:(id)identifier withOptions:(id)options forClient:(id)client error:(id*)error;
-(BOOL)_onQueue_removeArchiveForIdentifier:(id)identifier withOptions:(id)options forClient:(id)client error:(id*)error;
-(BOOL)createArchiveForIdentifier:(id)identifier withOptions:(id)options forClient:(id)client error:(id*)error;
-(BOOL)_onQueue_createArchiveForIdentifier:(id)identifier withOptions:(id)options forClient:(id)client error:(id*)error;
-(void)_onQueue_syncArchiveMapToDisk;
-(id)_archiveMapURL;
-(id)_archiveFileNameForIdentifier:(id)identifier;
-(id)init;
@end

