/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MIContainer.h"

@class MIExecutableBundle;

__attribute__((visibility("hidden")))
@interface MIBundleContainer : MIContainer {
	MIExecutableBundle* _bundle;
}
@property(readonly, assign) unsigned bundleMaxLinkedSDKVersion;
@property(readonly, assign) MIExecutableBundle* bundle;
+(id)updateSinfDataForAppWithIdentifier:(id)identifier sinfData:(id)data error:(id*)error;
+(id)tempPluginKitPluginBundleContainerWithIdentifier:(id)identifier error:(id*)error;
+(id)tempVPNPluginBundleContainerWithIdentifier:(id)identifier error:(id*)error;
+(id)tempAppBundleContainerWithIdentifier:(id)identifier error:(id*)error;
+(id)pluginKitPluginBundleContainerWithIdentifier:(id)identifier createIfNeeded:(BOOL)needed created:(BOOL*)created error:(id*)error;
+(id)vpnPluginBundleContainerWithIdentifier:(id)identifier createIfNeeded:(BOOL)needed created:(BOOL*)created error:(id*)error;
+(id)appBundleContainerWithIdentifier:(id)identifier createIfNeeded:(BOOL)needed created:(BOOL*)created error:(id*)error;
-(void).cxx_destruct;
-(void)clearDiskUsageCache;
-(unsigned long long)diskUsage;
-(BOOL)makeContainerLiveReplacingContainer:(id)container withError:(id*)error;
-(BOOL)captureBundleByMoving:(id)moving withError:(id*)error;
-(id)initWithContainer:(id)container;
@end

