/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSDictionary, MIExecutableBundle, NSString;

__attribute__((visibility("hidden")))
@interface MICodeSigningVerifier : XXUnknownSuperclass {
	MIExecutableBundle* _bundle;
	BOOL _allowAdhocSigning;
	BOOL _logResourceVerificationErrors;
	BOOL _validateSignatureOnly;
	BOOL _validatedByProfile;
	BOOL _isAdHocSigned;
	NSString* _signerIdentity;
	NSString* _codeInfoIdentifier;
	NSDictionary* _entitlements;
}
@property(readonly, assign) BOOL isAdHocSigned;
@property(readonly, assign) BOOL validatedByProfile;
@property(readonly, assign) NSDictionary* entitlements;
@property(readonly, assign) NSString* codeInfoIdentifier;
@property(readonly, assign) NSString* signerIdentity;
@property(assign) BOOL validateSignatureOnly;
@property(assign) BOOL logResourceVerificationErrors;
@property(assign) BOOL allowAdhocSigning;
+(id)errorStringForMISError:(int)miserror;
+(id)codeSigningVerifierForBundle:(id)bundle;
-(void).cxx_destruct;
-(BOOL)performValidationWithError:(id*)error;
-(id)initWithBundle:(id)bundle;
@end

