/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "MIFilesystemScannerDelegate.h"


__attribute__((visibility("hidden")))
@interface MIContainerProtectionMigrator : XXUnknownSuperclass <MIFilesystemScannerDelegate> {
}
-(BOOL)createBuiltInAppContainersWithError:(id*)error;
-(BOOL)scanExecutableBundle:(id)bundle inContainer:(id)container withError:(id*)error;
-(BOOL)scanBundle:(id)bundle withError:(id*)error;
-(BOOL)_setUpDataContainersForBundle:(id)bundle withError:(id*)error;
@end

