/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class MCMContainer, NSURL;

__attribute__((visibility("hidden")))
@interface MIContainer : XXUnknownSuperclass {
	MCMContainer* _container;
	unsigned _status;
}
@property(readonly, assign) unsigned status;
@property(readonly, assign) int contentClass;
@property(readonly, assign) NSURL* containerURL;
@property(readonly, assign) MCMContainer* container;
+(id)allContainersForIdentifier:(id)identifier options:(unsigned)options error:(id*)error;
+(id)_bundleContainerForIdentifier:(id)identifier error:(id*)error;
+(id)containersWithClass:(int)aClass error:(id*)error;
+(id)containerWithIdentifier:(id)identifier ofContentClass:(int)contentClass createIfNeeded:(BOOL)needed created:(BOOL*)created error:(id*)error;
+(id)tempContainerWithIdentifier:(id)identifier ofContentClass:(int)contentClass error:(id*)error;
-(void).cxx_destruct;
-(BOOL)captureStoreDataFromDirectory:(id)directory doCopy:(BOOL)copy failureIsFatal:(BOOL)fatal withError:(id*)error;
-(unsigned long long)diskUsage;
-(BOOL)purgeContentWithError:(id*)error;
-(BOOL)makeContainerLiveReplacingContainer:(id)container withError:(id*)error;
-(id)initWithContainer:(id)container;
@end

