/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface MIContainerRestoration : XXUnknownSuperclass {
}
+(BOOL)processRestoredContainerWithIdentifier:(id)identifier ofType:(int)type options:(id)options forClient:(id)client error:(id*)error;
@end

