/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MIContainer.h"

@class NSArray;

__attribute__((visibility("hidden")))
@interface MIDataContainer : MIContainer {
	NSArray* _groupContainerIdentifiers;
	int _contentProtectionClass;
	NSArray* _groupContainers;
}
@property(assign) int contentProtectionClass;
@property(readonly, assign) NSArray* groupContainers;
@property(retain) NSArray* referencedGroupContainerIdentifiers;
+(id)dataContainerForExecutableBundle:(id)executableBundle createIfNeeded:(BOOL)needed temporary:(BOOL)temporary created:(BOOL*)created error:(id*)error;
-(void).cxx_destruct;
-(void)makeSymlinkToBundleInContainerIfNeeded:(id)containerIfNeeded;
-(id)_oldCompatiblityLinkDestination;
-(id)_compatibilityLinkDestinationForBundleContainer:(id)bundleContainer;
-(id)setUpGroupContainersForReferencedIdentifiers:(id)referencedIdentifiers;
@end

