/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSArray;

__attribute__((visibility("hidden")))
@interface MIDataProtectionChangeOperation : XXUnknownSuperclass {
	NSArray* _urls;
	int _newClass;
	BOOL _retryIfLocked;
	BOOL _retried;
	int _operationType;
	id _retryStartBlock;
	id _completionBlock;
}
@property(copy) id completionBlock;
@property(copy) id retryStartBlock;
+(id)dataProtectionChangeOperationForURL:(id)url settingClass:(int)aClass retryingIfLocked:(BOOL)locked changeType:(int)type;
+(id)dataProtectionChangeOperationForURLs:(id)urls settingClass:(int)aClass retryingIfLocked:(BOOL)locked changeType:(int)type;
-(void).cxx_destruct;
-(void)performChangeOperation;
-(BOOL)_runChangeOperationNeedToRetry:(BOOL*)retry withError:(id*)error;
-(id)initWithURLs:(id)urls newClass:(int)aClass retryingIfLocked:(BOOL)locked changeType:(int)type;
@end

