/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSObject, NSMutableDictionary;
@protocol OS_dispatch_queue;

__attribute__((visibility("hidden")))
@interface MIDeveloperDiskImageTracker : XXUnknownSuperclass {
	NSObject<OS_dispatch_queue>* _mapAccessQueue;
	NSObject<OS_dispatch_queue>* _lsRegisterQueue;
	NSMutableDictionary* _map;
}
+(id)sharedTracker;
-(void).cxx_destruct;
-(void)imageMounted:(const char*)mounted;
-(void)checkDeveloperMount;
-(void)checkMountPoint:(id)point;
-(id)_onQueue_ScanDir:(id)dir;
-(void)_onQueue_RegisterAppsWithLS:(id)ls unregister:(id)unregister dir:(id)dir dirStatTime:(id)time;
-(void)recordLastLSDict:(id)dict;
-(void)recordLastLSDict:(id)dict forDir:(id)dir;
-(id)_dirStatTime:(id)time;
-(id)_dirMapURL;
-(id)init;
@end

