/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSArray;

__attribute__((visibility("hidden")))
@interface MIDiskUsageGatherer : XXUnknownSuperclass {
	NSArray* _identifiers;
	BOOL _calcStatic;
	BOOL _calcDynamic;
}
-(void).cxx_destruct;
-(id)gatherUsageInfoWithError:(id*)error;
-(id)_gatherForIdentifier:(id)identifier;
-(id)initWithIdentifiers:(id)identifiers options:(id)options;
@end

