/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MIBundle.h"

@class NSDictionary, NSString, NSURL;

__attribute__((visibility("hidden")))
@interface MIExecutableBundle : MIBundle {
	BOOL _validateSignatureOnly;
	BOOL _validatedByProfile;
	unsigned _codeSignatureVerificationState;
	NSString* _signerIdentity;
	NSString* _codeInfoIdentifier;
	NSDictionary* _entitlements;
}
@property(readonly, assign) BOOL validatedByProfile;
@property(readonly, assign) NSDictionary* entitlements;
@property(readonly, assign) NSString* codeInfoIdentifier;
@property(readonly, assign) NSString* signerIdentity;
@property(readonly, assign) unsigned codeSignatureVerificationState;
@property(assign) BOOL validateSignatureOnly;
@property(readonly, assign) unsigned maxLinkedSDKVersion;
@property(readonly, assign) int dataContainerContentClass;
@property(readonly, assign) BOOL isPlaceholder;
@property(readonly, assign) BOOL needsSinf;
@property(readonly, assign) NSURL* rootSupfURL;
@property(readonly, assign) NSURL* rootSuppURL;
@property(readonly, assign) NSURL* rootSinfURL;
@property(readonly, assign) NSURL* executableURL;
@property(readonly, assign) NSString* executableName;
-(void).cxx_destruct;
-(id)purchaserDSIDWithError:(id*)error;
-(void)removeSinf;
-(BOOL)replicateRootSinfWithError:(id*)error;
-(BOOL)updateSinfWithData:(id)data error:(id*)error;
-(BOOL)_writeSinfData:(id)data toURLs:(id)urls error:(id*)error;
-(id)sinfURLsWithError:(id*)error;
-(id)_sinfSubPaths;
-(id)vpnPluginIdentifiers;
-(id)_dataContainerCreatingIfNeeded:(BOOL)needed makeLive:(BOOL)live checkIfNeeded:(BOOL)needed3 created:(BOOL*)created error:(id*)error;
-(id)dataContainerCreatingIfNeeded:(BOOL)needed makeLive:(BOOL)live created:(BOOL*)created error:(id*)error;
-(id)dataContainerWithError:(id*)error;
-(Class)dataContainerClass;
-(BOOL)performCodeSigningValidationWithError:(id*)error;
-(BOOL)_useInternalValidation;
-(BOOL)needsDataContainer;
-(BOOL)_validateWithError:(id*)error;
@end

