/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@protocol MIFilesystemScannerDelegate
-(BOOL)scanExecutableBundle:(id)bundle inContainer:(id)container withError:(id*)error;
-(BOOL)scanBundle:(id)bundle withError:(id*)error;
@end

