/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface MIFileManager : XXUnknownSuperclass {
}
+(id)defaultManager;
-(id)realPathForURL:(id)url ifChildOfURL:(id)url2;
-(id)realPathForURL:(id)url allowNonExistentPathComponents:(BOOL)components;
-(id)_realPathWhatExistsInPath:(id)path;
-(BOOL)captureStoreDataFromDirectory:(id)directory toDirectory:(id)directory2 doCopy:(BOOL)copy failureIsFatal:(BOOL)fatal withError:(id*)error;
-(BOOL)setDataProtectionClassOfItemAtURL:(id)url toClass:(int)aClass ifPredicate:(id)predicate error:(id*)error;
-(BOOL)dataProtectionClassOfItemAtURL:(id)url class:(int*)aClass error:(id*)error;
-(BOOL)itemDoesNotExistAtURL:(id)url;
-(BOOL)itemExistsAtURL:(id)url;
-(id)destinationOfSymbolicLinkAtURL:(id)url error:(id*)error;
-(BOOL)createSymbolicLinkAtURL:(id)url withDestinationURL:(id)destinationURL error:(id*)error;
-(id)urlsForItemsInDirectoryAtURL:(id)url error:(id*)error;
-(BOOL)standardizeOwnershipAtURL:(id)url toUID:(unsigned)uid GID:(unsigned)gid error:(id*)error;
-(id)createTemporaryDirectoryInDirectoryURL:(id)directoryURL error:(id*)error;
-(BOOL)moveItemAtURL:(id)url toURL:(id)url2 error:(id*)error;
-(BOOL)copyItemAtURL:(id)url toURL:(id)url2 error:(id*)error;
-(BOOL)moveItemIfExistsAtURL:(id)url toURL:(id)url2 error:(id*)error;
-(BOOL)copyItemIfExistsAtURL:(id)url toURL:(id)url2 error:(id*)error;
-(BOOL)_moveItemAtURL:(id)url toURL:(id)url2 failIfSrcMissing:(BOOL)missing error:(id*)error;
-(BOOL)_copyItemAtURL:(id)url toURL:(id)url2 failIfSrcMissing:(BOOL)missing error:(id*)error;
-(BOOL)createDirectoryAtURL:(id)url withIntermediateDirectories:(BOOL)intermediateDirectories mode:(unsigned short)mode error:(id*)error;
-(BOOL)createDirectoryAtURL:(id)url withIntermediateDirectories:(BOOL)intermediateDirectories mode:(unsigned short)mode class:(int)aClass error:(id*)error;
-(BOOL)removeItemAtURL:(id)url error:(id*)error;
@end

