/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSDictionary, NSURL, NSSet, NSArray;

__attribute__((visibility("hidden")))
@interface MIGlobalConfiguration : XXUnknownSuperclass {
	NSURL* _homePath;
	NSURL* _rootPath;
	NSURL* _carrierBundlesDir;
	NSURL* _stagingRoot;
	NSURL* _systemAppsDir;
	NSURL* _internalAppsDir;
	NSURL* _developerAppsDir;
	NSURL* _factoryMountDir;
	NSURL* _systemFrameworksRootDirectory;
	NSURL* _internalFrameworksRootDirectory;
	NSURL* _developerFrameworksRootDirectory;
	NSURL* _dataDir;
	NSURL* _archiveDir;
	NSURL* _cachesDir;
	NSSet* _allFrameworksDirectories;
	NSDictionary* _systemAppBundleIDToInfoMap;
	NSDictionary* _internalAppBundleIDToInfoMap;
	BOOL _lowerInstallPriority;
	BOOL _skipDeviceFamilyCheck;
	BOOL _allowPatchWithoutSinf;
	unsigned _uid;
	unsigned _gid;
}
@property(readonly, assign) NSURL* oldGroupContainersPath;
@property(readonly, assign) NSURL* oldInstallMapPath;
@property(readonly, assign) NSURL* oldContainerPath;
@property(readonly, assign) unsigned gid;
@property(readonly, assign) unsigned uid;
@property(readonly, assign) NSDictionary* diskImageAppBundleIDToInfoMap;
@property(readonly, assign) NSDictionary* internalAppBundleIDToInfoMap;
@property(readonly, assign) NSDictionary* systemAppBundleIDToInfoMap;
@property(readonly, assign) NSSet* builtInApplicationBundleIDs;
@property(readonly, assign) NSSet* installationBlacklist;
@property(readonly, assign) NSArray* appUserDataItemNames;
@property(readonly, assign) NSArray* appBundleMetadataItemNames;
@property(readonly, assign) NSURL* cachesDirectory;
@property(readonly, assign) NSURL* archiveDirectory;
@property(readonly, assign) NSURL* dataDirectory;
@property(readonly, assign) NSSet* allFrameworksDirectories;
@property(readonly, assign) NSURL* developerFrameworksRootDirectory;
@property(readonly, assign) NSURL* internalFrameworksRootDirectory;
@property(readonly, assign) NSURL* systemFrameworksRootDirectory;
@property(readonly, assign) NSURL* homeDirectory;
@property(readonly, assign) NSURL* factoryMountDirectory;
@property(readonly, assign) NSURL* developerAppsDirectory;
@property(readonly, assign) NSURL* internalAppsDirectory;
@property(readonly, assign) NSURL* systemAppsDirectory;
@property(readonly, assign) NSURL* logDirectory;
@property(readonly, assign) NSURL* stagingRoot;
@property(readonly, assign) NSURL* carrierBundlesDirectory;
@property(readonly, assign) BOOL allowPatchWithoutSinf;
@property(readonly, assign) BOOL skipDeviceFamilyCheck;
@property(readonly, assign) BOOL lowerInstallPriority;
+(id)sharedInstance;
-(void).cxx_destruct;
-(id)diskImageApplicationsDirectories;
-(void)reScanInternalApps;
-(void)reScanSystemApps;
-(id)_bundleIDMapForAppsInDirectory:(id)directory;
-(id)init;
@end

