/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MIDataContainer.h"


__attribute__((visibility("hidden")))
@interface MIGroupContainer : MIDataContainer {
}
+(id)groupContainerWithIdentifier:(id)identifier createIfNeeded:(BOOL)needed error:(id*)error;
@end

