/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MIInstallableBundle.h"


__attribute__((visibility("hidden")))
@interface MIInstallableParallelPlaceholder : MIInstallableBundle {
}
-(BOOL)performInstallationWithError:(id*)error;
-(id)initWithBundle:(id)bundle inStagingRoot:(id)stagingRoot packageFormat:(int)format userOptions:(id)options existingBundleContainer:(id)container error:(id*)error;
@end

