/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSDictionary, NSURL, MIClientConnection;

__attribute__((visibility("hidden")))
@interface MIInstaller : XXUnknownSuperclass {
	NSURL* _path;
	NSDictionary* _options;
	MIClientConnection* _client;
	NSURL* _stagingRoot;
	NSURL* _stagingPath;
	int _packageFormat;
	NSDictionary* _receipt;
}
@property(readonly, assign) NSDictionary* receipt;
+(id)installerForURL:(id)url withOptions:(id)options forClient:(id)client;
-(void).cxx_destruct;
-(BOOL)performInstallationWithError:(id*)error;
-(BOOL)_extractPackageWithError:(id*)error;
-(BOOL)_setupPackageStateWithError:(id*)error;
-(void)_fireCallbackWithStatus:(id)status;
-(void)_fireCallbackWithStatus:(id)status percentComplete:(unsigned)complete;
-(id)initWithURL:(id)url options:(id)options forClient:(id)client;
-(id)init;
@end

