/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MIInstallable.h"
#import "installd-Structs.h"

@class MIExecutableBundle, NSArray, MIBundleContainer, MIDataContainer;

__attribute__((visibility("hidden")))
@interface MIInstallableBundle : MIInstallable {
	BOOL _isPlaceholderInstall;
	SBSApplicationTerminationAssertionRef _sbAssertion;
	NSArray* _pluginBundles;
	NSArray* _frameworkBundles;
	BOOL _checkIncomingUpgradeEntitlement;
	MIBundleContainer* _existingBundleContainer;
	MIBundleContainer* _bundleContainer;
	MIDataContainer* _dataContainer;
	NSArray* _pluginDataContainers;
}
@property(readonly, assign) BOOL checkIncomingUpgradeEntitlement;
@property(readonly, assign) NSArray* frameworkBundles;
@property(readonly, assign) NSArray* pluginDataContainers;
@property(readonly, assign) NSArray* pluginBundles;
@property(retain) MIDataContainer* dataContainer;
@property(retain) MIBundleContainer* bundleContainer;
@property(readonly, assign) MIBundleContainer* existingBundleContainer;
@property(readonly, assign) BOOL isPlaceholderInstall;
@property(retain) MIExecutableBundle* bundle;
-(void).cxx_destruct;
-(id)launchServicesDictionariesWithError:(id*)error;
-(BOOL)finalizeInstallationWithError:(id*)error;
-(BOOL)_refreshUUIDForContainer:(id)container withError:(id*)error;
-(BOOL)postFlightInstallationWithError:(id*)error;
-(BOOL)_captureVPNPluginWithError:(id*)error;
-(BOOL)_postFlightPluginsWithError:(id*)error;
-(BOOL)performInstallationWithError:(id*)error;
-(BOOL)_captureDataFromStagingRootOrBundle:(id)stagingRootOrBundle toContainer:(id)container withError:(id*)error;
-(BOOL)_writeOptionsDataToBundle:(id)bundle orContainer:(id)container error:(id*)error;
-(BOOL)_writeData:(id)data toFileNamed:(id)fileNamed inURL:(id)url;
-(BOOL)performVerificationWithError:(id*)error;
-(BOOL)performPreflightWithError:(id*)error;
-(BOOL)_checkCanInstallWithError:(id*)error;
-(void)_fixupCodeResources;
-(void)_installEmbeddedProfileInBundle:(id)bundle;
-(void)_installEmbeddedProfiles;
-(BOOL)_verifyBundleMetadataWithError:(id*)error;
-(BOOL)_verifySubBundleMetadataWithError:(id*)error;
-(void)dealloc;
-(id)initWithBundle:(id)bundle inStagingRoot:(id)stagingRoot packageFormat:(int)format userOptions:(id)options existingBundleContainer:(id)container error:(id*)error;
@end

