/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSDictionary, MIBundle, NSURL;

__attribute__((visibility("hidden")))
@interface MIInstallable : XXUnknownSuperclass {
	MIBundle* _bundle;
	BOOL _modifyExistingContainers;
	NSDictionary* _userOptions;
	NSURL* _stagingRootURL;
	int _packageFormat;
	id _progressBlock;
}
@property(copy) id progressBlock;
@property(readonly, assign) int packageFormat;
@property(readonly, assign) NSURL* stagingRootURL;
@property(readonly, assign) NSDictionary* userOptions;
@property(retain) MIBundle* bundle;
+(id)installablesAtURL:(id)url packageFormat:(int)format userOptions:(id)options error:(id*)error;
+(id)_manifestPathForBase:(id)base withIdentifier:(id)identifier;
-(void).cxx_destruct;
-(id)description;
-(id)launchServicesDictionariesWithError:(id*)error;
-(BOOL)finalizeInstallationWithError:(id*)error;
-(BOOL)postFlightInstallationWithError:(id*)error;
-(BOOL)performInstallationWithError:(id*)error;
-(BOOL)performVerificationWithError:(id*)error;
-(BOOL)performPreflightWithError:(id*)error;
-(BOOL)applyPatchWithError:(id*)error;
-(id)initWithBundle:(id)bundle inStagingRoot:(id)stagingRoot packageFormat:(int)format userOptions:(id)options error:(id*)error;
@end

