/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MIInstallableBundle.h"

@class NSString, NSURL;

__attribute__((visibility("hidden")))
@interface MIInstallableBundlePatch : MIInstallableBundle {
	NSString* _existingBundleVersion;
	NSString* _existingBundleShortVersion;
	NSString* _newBundleVersion;
	NSString* _newBundleShortVersion;
	NSURL* _manifestURL;
}
@property(readonly, assign) NSURL* manifestURL;
-(void).cxx_destruct;
-(BOOL)performVerificationWithError:(id*)error;
-(BOOL)applyPatchWithError:(id*)error;
-(id)initWithBundle:(id)bundle inStagingRoot:(id)stagingRoot packageFormat:(int)format userOptions:(id)options manifestURL:(id)url existingBundleContainer:(id)container error:(id*)error;
@end

