/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MIInstallable.h"


__attribute__((visibility("hidden")))
@interface MIInstallableCarrierBundle : MIInstallable {
}
-(BOOL)performInstallationWithError:(id*)error;
@end

