/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class MIExecutableBundle, MIBundleContainer, MIDataContainer, NSString;

__attribute__((visibility("hidden")))
@interface MIInstalledInfoGatherer : XXUnknownSuperclass {
	MIExecutableBundle* _bundle;
	MIExecutableBundle* _builtInAppParallelPlaceholderBundle;
	MIBundleContainer* _bundleContainer;
	MIDataContainer* _dataContainer;
	NSString* _pluginOwnerBundleIdentifier;
}
+(BOOL)bundleAtURLIsPlaceholder:(id)urlisPlaceholder;
+(BOOL)markBundleAsPlaceholder:(id)placeholder withError:(id*)error;
+(id)infoPlistKeysToLoad;
-(void).cxx_destruct;
-(id)launchServicesDictionaryWithError:(id*)error;
-(id)_staticDiskUsage;
-(id)_groupContainersDictionary;
-(id)_sandboxEnvironment;
-(id)_determineApplicationType;
-(id)initWithPluginBundle:(id)pluginBundle inBundleIdentifier:(id)bundleIdentifier dataContainer:(id)container;
-(id)initWithBundleContainer:(id)bundleContainer dataContainer:(id)container;
-(id)initWithBundleContainer:(id)bundleContainer;
-(id)initWithBundle:(id)bundle dataContainer:(id)container;
-(void)_fixUpForBuiltInAppParallelPlaceholder;
@end

