/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "MIFilesystemScannerDelegate.h"

@class NSDictionary, NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface MILaunchServicesDatabaseGatherer : XXUnknownSuperclass <MIFilesystemScannerDelegate> {
	NSMutableDictionary* _systemApps;
	NSMutableDictionary* _userApps;
	NSMutableDictionary* _internalApps;
	NSMutableDictionary* _pluginKitPlugins;
	NSMutableDictionary* _vpnPlugins;
}
@property(readonly, assign) NSDictionary* receipt;
+(id)entryForBundle:(id)bundle inContainer:(id)container withError:(id*)error;
+(id)dictOfPluginKitPluginsInBundle:(id)bundle withError:(id*)error;
-(void).cxx_destruct;
-(BOOL)performGatherWithError:(id*)error;
-(BOOL)scanExecutableBundle:(id)bundle inContainer:(id)container withError:(id*)error;
-(id)_dictForEntry:(id)entry;
-(BOOL)scanBundle:(id)bundle withError:(id*)error;
-(id)init;
@end

