/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MIDataContainer.h"


__attribute__((visibility("hidden")))
@interface MIPluginDataContainer : MIDataContainer {
}
+(id)pluginDataContainerWithIdentifier:(id)identifier createIfNeeded:(BOOL)needed created:(BOOL*)created error:(id*)error;
@end

