/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MIExecutableBundle.h"

@class NSDictionary, NSString;

__attribute__((visibility("hidden")))
@interface MIPluginKitPluginBundle : MIExecutableBundle {
	NSDictionary* _overlaidInfoPlist;
	NSString* _parentBundleID;
}
@property(readonly, assign) NSString* extensionPointIdentifier;
@property(readonly, assign) NSString* parentBundleID;
+(id)bundleForURL:(id)url parentBundle:(id)bundle error:(id*)error;
-(void).cxx_destruct;
-(BOOL)validateBundleMetadataWithError:(id*)error;
-(BOOL)_validateNSExtensionWithOverlaidDictionary:(id)overlaidDictionary error:(id*)error;
-(BOOL)_validateXPCServiceWithOverlaidDictionary:(id)overlaidDictionary error:(id*)error;
-(id)dataContainerCreatingIfNeeded:(BOOL)needed makeLive:(BOOL)live created:(BOOL*)created error:(id*)error;
-(id)dataContainerWithError:(id*)error;
-(id)overlaidInfoPlistWithError:(id*)error;
-(id)_overlayDictionary:(id)dictionary onDictionary:(id)dictionary2;
-(Class)dataContainerClass;
-(id)initWithBundleURL:(id)bundleURL parentBundle:(id)bundle error:(id*)error;
@end

