/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface MISystemAppDataContainerMigrator : XXUnknownSuperclass {
}
-(BOOL)performMigrationWithError:(id*)error;
-(BOOL)_migrateAppsWithError:(id*)error;
-(BOOL)_migrateContainer:(id)container withError:(id*)error;
-(BOOL)_migrateBundleDataInContainer:(id)container forBundle:(id)bundle error:(id*)error;
-(BOOL)_migrateBundleDataItem:(id)item fromContainer:(id)container toContainer:(id)container3 error:(id*)error;
-(id)_containerBundleIdentifierForOldContainer:(id)oldContainer;
-(id)init;
@end

