/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSDictionary, NSObject, NSMutableDictionary;
@protocol OS_dispatch_queue;

__attribute__((visibility("hidden")))
@interface MIUninstalledAppList : XXUnknownSuperclass {
	NSObject<OS_dispatch_queue>* _listQueue;
	NSMutableDictionary* _uninstalledList;
}
@property(readonly, assign) NSDictionary* uninstalledDictionary;
+(id)sharedList;
-(void).cxx_destruct;
-(void)removeIdentifiers:(id)identifiers;
-(void)addIdentifier:(id)identifier;
-(void)preflightUninstalledMap;
-(void)_onQueue_setUninstalledList:(id)list;
-(id)_onQueue_uninstalledList;
-(id)_mapPath;
-(id)init;
@end

