/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSArray;

__attribute__((visibility("hidden")))
@interface MIUninstallNotifier : XXUnknownSuperclass {
	NSArray* _removals;
}
-(void).cxx_destruct;
-(void)performRemovalWithCompletionBlock:(id)completionBlock;
-(id)initWithContainersToRemove:(id)remove;
@end

