/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSDictionary, NSArray, MIClientConnection;

__attribute__((visibility("hidden")))
@interface MIUninstaller : XXUnknownSuperclass {
	NSArray* _identifiers;
	NSDictionary* _options;
	MIClientConnection* _client;
	unsigned _percentComplete;
	NSDictionary* _receipt;
}
@property(readonly, assign) NSDictionary* receipt;
+(id)uninstallerForIdentifiers:(id)identifiers withOptions:(id)options forClient:(id)client;
-(void).cxx_destruct;
-(BOOL)performUninstallationWithError:(id*)error;
-(id)_uninstallBundleWithIdentifier:(id)identifier error:(id*)error;
-(BOOL)_uninstallUserStuffForIdentifier:(id)identifier error:(id*)error;
-(void)_fireCallbackWithStatus:(id)status;
-(void)_fireCallbackWithStatus:(id)status percentComplete:(unsigned)complete;
-(id)initWithIdentifiers:(id)identifiers options:(id)options forClient:(id)client;
@end

