/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface XXUnknownSuperclass (MobileInstallationAdditions)
+(id)stringWithFileSystemRepresentation:(const char*)fileSystemRepresentation;
+(id)stringWithFileSystemRepresentation:(const char*)fileSystemRepresentation length:(unsigned long)length;
@end

@interface XXUnknownSuperclass (MobileInstallationOptions)
+(id)MI_dictionaryWithContentsOfURL:(id)url options:(unsigned)options error:(id*)error;
@end

@interface XXUnknownSuperclass (MobileInstallationAdditions)
+(id)MI_dictionaryWithContentsOfURL:(id)url options:(unsigned)options error:(id*)error;
-(BOOL)MI_writeToURL:(id)url format:(unsigned)format options:(unsigned)options error:(id*)error;
@end

